---
title: "2016_Full"
author: "Paul Beeman"
date: "7/21/2018"
output: html_document
---

```{r age}
Demo_Youth_2016 <- data.frame(Age = X2016_Youth_Survey$age)
Demo_Youth_2016$Birth_Year <- 2016 - Demo_Youth_2016$Age


```

```{r sex/gender}
Demo_Youth_2016$Gender <- recode(X2016_Youth_Survey$gender, "Error" ="Unknown")

```

```{r sexual orientation}
Demo_Youth_2016$Sexual_Orientation <- recode(as.character(X2016_Youth_Survey$sexOrient), "Error" = "Unknown", "Unsure or Questioning" = "Unsure/questioning")

```

```{r race Ethnicity}
Demo_Youth_2016$Ethnicity <- ifelse(grepl("African", X2016_Youth_Survey$race), "African American", ifelse(grepl(" Latino", X2016_Youth_Survey$hispanic), "Latino", ifelse(grepl("White", X2016_Youth_Survey$race), "European American", "Other Ethnicity")))

Demo_Youth_2016$Race_Full <- X2016_Youth_Survey$race

Demo_Youth_2016$Race_Recode <- ifelse(grepl("African", X2016_Youth_Survey$race), "African American", ifelse(grepl("White", X2016_Youth_Survey$race), "European American", ifelse(grepl("Error", X2016_Youth_Survey$race), "Unknown", "Other Ethnicity")))


```

```{r Veteran}
#Veteran (known or unknown discharge status)
Demo_Youth_2016$Veteran <- recode(as.character(X2016_Youth_Survey$veteran), "No" = 0, "Yes" =1, .default = 2, .missing = 2)

```

```{r chronic}
Demo_Youth_2016$Chronic_Condition <- recode(X2016_Youth_Survey$chronCond, "No" = 0, "Yes" = 1, .default = 2, .missing = 2) 

Demo_Youth_2016$Chronic_Time <-  recode(X2016_Youth_Survey$chronTime, "No" = 0, "Yes" = 1, .default = 2, .missing = 2)

Demo_Youth_2016$Chronic <-  recode(X2016_Youth_Survey$chronic, "Other" = 0, "Chronic" = 1, .default = 2, .missing = 2)


```


```{r time variables}
X2016_Youth_Survey$rawHowLongHomelessThisTimeDays[is.na(X2016_Youth_Survey$rawHowLongHomelessThisTimeDays)] <- 0

X2016_Youth_Survey$rawHowLongHomelessThisTimeWeeks[is.na(X2016_Youth_Survey$rawHowLongHomelessThisTimeWeeks)] <- 0

X2016_Youth_Survey$rawHowLongHomelessThisTimeMonths[is.na(X2016_Youth_Survey$rawHowLongHomelessThisTimeMonths)] <- 0

X2016_Youth_Survey$rawHowLongHomelessThisTimeYears[is.na(X2016_Youth_Survey$rawHowLongHomelessThisTimeYears)] <- 0
#Duration of Current Episode

Demo_Youth_2016$Current_Stint_Duration <-  ifelse(as.numeric(as.character(X2016_Youth_Survey$rawHowLongHomelessThisTimeYears)) >= 1, "12+ Months", ifelse(as.numeric(as.character(X2016_Youth_Survey$rawHowLongHomelessThisTimeMonths)) >= 6, "6-11 Months", ifelse(as.numeric(as.character(X2016_Youth_Survey$rawHowLongHomelessThisTimeMonths)) >= 4, "4-5 Months", ifelse(as.numeric(as.character(X2016_Youth_Survey$rawHowLongHomelessThisTimeMonths)) >= 1, "1-3 Months", ifelse(as.numeric(as.character(X2016_Youth_Survey$rawHowLongHomelessThisTimeWeeks)) >= 1, "Up to 1 Month", ifelse(as.numeric(as.character(X2016_Youth_Survey$rawHowLongHomelessThisTimeDays)) >=1, "Up to 1 Month", "Unknown"))))))

#detailed



Demo_Youth_2016$Current_Stint_Duration_Detailed <- X2016_Youth_Survey$rawHowLongHomelessThisTimeDays + X2016_Youth_Survey$rawHowLongHomelessThisTimeMonths*30 + X2016_Youth_Survey$rawHowLongHomelessThisTimeWeeks*7 + X2016_Youth_Survey$rawHowLongHomelessThisTimeYears*365

#Times homeless in the past 3 years
Demo_Youth_2016$Times_Homeless_3yrs <- recode(X2016_Youth_Survey$rawInPast3YrsNumEpisodesHomeless, "1 time" ="1 time", "2-3 times" = "2 to 3 times", "4 or more times" = "4 or more times", .default = "Unknown", .missing = "Unknown")

#SPA
Demo_Youth_2016$SPA <- X2016_Youth_Survey$SPA

#Census Tract 
Demo_Youth_2016$Census_Tract <- X2016_Youth_Survey$CensusTract


```
```{r weights}
Demo_Youth_2016$Weights <- X2016_Youth_Survey$YOUTH_WEIGHT


```

```{r write csv}
write.csv(Demo_Youth_2016, file = "Demo_2016_Youth.csv")
```

```{r view}
View(Demo_Youth_2016)


```